manual

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -587,12 +587,22 @@ jobs:
       with:
         repository: DOCGroup/MPC
         path: MPC
+    - name: setup gtest
+      run: |
+        cd OpenDDS/tests/googletest
+        git submodule init
+        git submodule update
+        mkdir build
+        cd build
+        mkdir install
+        cmake -DCMAKE_INSTALL_PREFIX=./install ..
+        cmake --build . --target install
     - name: configure OpenDDS
       if: steps.cache-artifact.outputs.cache-hit != 'true'
       run: |
         cd OpenDDS
         ls tests/googletest
-        ./configure --tests --gtest=$GITHUB_WORKSPACE/OpenDDS/tests/googletest --safety-profile --no-rapidjson --mpc=$GITHUB_WORKSPACE/MPC
+        ./configure --tests --gtest=$GITHUB_WORKSPACE/OpenDDS/tests/googletest/build/install --safety-profile --no-rapidjson --mpc=$GITHUB_WORKSPACE/MPC
     - name: build everything
       if: steps.cache-artifact.outputs.cache-hit != 'true'
       run: |
@@ -647,91 +657,91 @@ jobs:
         cat "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"
         if ! grep -q 'Failures: 0' "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"; then echo "::error file=latest.txt,line=0,col=0::Test Failures: see 'Test Results: ${{ github.job }}'"; fi
 
-  u18_bsafe_js0_FM-1f:
+  # u18_bsafe_js0_FM-1f:
 
-    runs-on: ubuntu-18.04
+  #   runs-on: ubuntu-18.04
 
-    needs: wait_cancel_previous
+  #   needs: wait_cancel_previous
 
-    steps:
-    - name: checkout OpenDDS
-      uses: actions/checkout@v2.3.4
-      with:
-        path: OpenDDS
-        submodules: true
-    - name: checkout autobuild
-      uses: actions/checkout@v2.3.4
-      with:
-        repository: DOCGroup/autobuild
-        path: autobuild
-    - name: install xerces
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: sudo apt-get -y install libxerces-c-dev
-    - name: checkout MPC
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      uses: actions/checkout@v2.3.4
-      with:
-        repository: DOCGroup/MPC
-        path: MPC
-    - name: configure OpenDDS
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: |
-        cd OpenDDS
-        ls tests/googletest
-        ./configure --tests --gtest=$GITHUB_WORKSPACE/OpenDDS/tests/googletest --safety-profile=base --no-rapidjson --no-built-in-topics --mpc=$GITHUB_WORKSPACE/MPC
-    - name: build everything
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: |
-        cd OpenDDS
-        make -j4
-    - name: check build configuration
-      shell: bash
-      run: |
-        cd OpenDDS/build/target
-        . setenv.sh
-        tools/scripts/show_build_config.pl
-    - name: run OpenDDS tests
-      shell: bash
-      run: |
-        cd OpenDDS/build/target
-        . setenv.sh
-        mkdir ${{ github.job }}_autobuild_workspace
-        cd ${{ github.job }}_autobuild_workspace
-        echo using commit $TRIGGERING_COMMIT for SHA
-        echo $TRIGGERING_COMMIT >> ./SHA
-        cat > config.xml <<EOF
-        <autobuild>
-        <configuration>
-        <variable name="log_file" value="output.log"/>
-        <variable name="log_root" value="$DDS_ROOT/${{ github.job }}_autobuild_workspace"/>
-        <variable name="project_root" value="$DDS_ROOT"/>
-        <variable name="root" value="$DDS_ROOT/${{ github.job }}_autobuild_workspace"/>
-        <variable name="junit_xml_output" value="Tests"/>
-        </configuration>
-        <command name="log" options="on"/>
-        <command name="print_os_version"/>
-        <command name="print_env_vars"/>
-        <command name="print_ace_config"/>
-        <command name="print_make_version"/>
-        <command name="check_compiler" options="gcc"/>
-        <command name="print_perl_version"/>
-        <command name="print_autobuild_config"/>
-        <command name="auto_run_tests" options="script_path=tests dir=$GITHUB_WORKSPACE/OpenDDS -Config RTPS -Config LINUX -Config XERCES3 -Config CXX11 -Config OPENDDS_SAFETY_PROFILE -Config NO_BUILT_IN_TOPICS -Config DDS_NO_CONTENT_SUBSCRIPTION -Config DDS_NO_CONTENT_FILTERED_TOPIC -Config DDS_NO_MULTI_TOPIC -Config DDS_NO_QUERY_CONDITION -Config DDS_NO_OWNERSHIP_KIND_EXCLUSIVE -Config DDS_NO_OBJECT_MODEL_PROFILE -Config DDS_NO_PERSISTENCE_PROFILE  -Config GH_ACTIONS"/>
-        <command name="log" options="off"/>
-        <command name="process_logs" options="prettify"/>
-        </autobuild>
-        EOF
-        $GITHUB_WORKSPACE/autobuild/autobuild.pl "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/config.xml"
-    - name: upload autobuild output
-      uses: actions/upload-artifact@v2
-      with:
-        name: ${{ github.job }}_autobuild_output
-        path: OpenDDS/build/target/${{ github.job }}_autobuild_workspace
-    - name: check results
-      shell: bash
-      run: |
-        cat "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"
-        if ! grep -q 'Failures: 0' "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"; then echo "::error file=latest.txt,line=0,col=0::Test Failures: see 'Test Results: ${{ github.job }}'"; fi
+  #   steps:
+  #   - name: checkout OpenDDS
+  #     uses: actions/checkout@v2.3.4
+  #     with:
+  #       path: OpenDDS
+  #       submodules: true
+  #   - name: checkout autobuild
+  #     uses: actions/checkout@v2.3.4
+  #     with:
+  #       repository: DOCGroup/autobuild
+  #       path: autobuild
+  #   - name: install xerces
+  #     if: steps.cache-artifact.outputs.cache-hit != 'true'
+  #     run: sudo apt-get -y install libxerces-c-dev
+  #   - name: checkout MPC
+  #     if: steps.cache-artifact.outputs.cache-hit != 'true'
+  #     uses: actions/checkout@v2.3.4
+  #     with:
+  #       repository: DOCGroup/MPC
+  #       path: MPC
+  #   - name: configure OpenDDS
+  #     if: steps.cache-artifact.outputs.cache-hit != 'true'
+  #     run: |
+  #       cd OpenDDS
+  #       ls tests/googletest
+  #       ./configure --tests --gtest=$GITHUB_WORKSPACE/OpenDDS/tests/googletest --safety-profile=base --no-rapidjson --no-built-in-topics --mpc=$GITHUB_WORKSPACE/MPC
+  #   - name: build everything
+  #     if: steps.cache-artifact.outputs.cache-hit != 'true'
+  #     run: |
+  #       cd OpenDDS
+  #       make -j4
+  #   - name: check build configuration
+  #     shell: bash
+  #     run: |
+  #       cd OpenDDS/build/target
+  #       . setenv.sh
+  #       tools/scripts/show_build_config.pl
+  #   - name: run OpenDDS tests
+  #     shell: bash
+  #     run: |
+  #       cd OpenDDS/build/target
+  #       . setenv.sh
+  #       mkdir ${{ github.job }}_autobuild_workspace
+  #       cd ${{ github.job }}_autobuild_workspace
+  #       echo using commit $TRIGGERING_COMMIT for SHA
+  #       echo $TRIGGERING_COMMIT >> ./SHA
+  #       cat > config.xml <<EOF
+  #       <autobuild>
+  #       <configuration>
+  #       <variable name="log_file" value="output.log"/>
+  #       <variable name="log_root" value="$DDS_ROOT/${{ github.job }}_autobuild_workspace"/>
+  #       <variable name="project_root" value="$DDS_ROOT"/>
+  #       <variable name="root" value="$DDS_ROOT/${{ github.job }}_autobuild_workspace"/>
+  #       <variable name="junit_xml_output" value="Tests"/>
+  #       </configuration>
+  #       <command name="log" options="on"/>
+  #       <command name="print_os_version"/>
+  #       <command name="print_env_vars"/>
+  #       <command name="print_ace_config"/>
+  #       <command name="print_make_version"/>
+  #       <command name="check_compiler" options="gcc"/>
+  #       <command name="print_perl_version"/>
+  #       <command name="print_autobuild_config"/>
+  #       <command name="auto_run_tests" options="script_path=tests dir=$GITHUB_WORKSPACE/OpenDDS -Config RTPS -Config LINUX -Config XERCES3 -Config CXX11 -Config OPENDDS_SAFETY_PROFILE -Config NO_BUILT_IN_TOPICS -Config DDS_NO_CONTENT_SUBSCRIPTION -Config DDS_NO_CONTENT_FILTERED_TOPIC -Config DDS_NO_MULTI_TOPIC -Config DDS_NO_QUERY_CONDITION -Config DDS_NO_OWNERSHIP_KIND_EXCLUSIVE -Config DDS_NO_OBJECT_MODEL_PROFILE -Config DDS_NO_PERSISTENCE_PROFILE  -Config GH_ACTIONS"/>
+  #       <command name="log" options="off"/>
+  #       <command name="process_logs" options="prettify"/>
+  #       </autobuild>
+  #       EOF
+  #       $GITHUB_WORKSPACE/autobuild/autobuild.pl "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/config.xml"
+  #   - name: upload autobuild output
+  #     uses: actions/upload-artifact@v2
+  #     with:
+  #       name: ${{ github.job }}_autobuild_output
+  #       path: OpenDDS/build/target/${{ github.job }}_autobuild_workspace
+  #   - name: check results
+  #     shell: bash
+  #     run: |
+  #       cat "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"
+  #       if ! grep -q 'Failures: 0' "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/latest.txt"; then echo "::error file=latest.txt,line=0,col=0::Test Failures: see 'Test Results: ${{ github.job }}'"; fi
 
 #   ACE_TAO_u18_d0i0v1_sec_js0_FM-06:
 
@@ -2271,58 +2281,58 @@ jobs:
 #   #       cat "$GITHUB_WORKSPACE/OpenDDS/${{ github.job }}_autobuild_workspace/latest.txt"
 #   #       if ! grep -q 'Failures: 0' "$GITHUB_WORKSPACE/OpenDDS/${{ github.job }}_autobuild_workspace/latest.txt"; then echo "::error file=latest.txt,line=0,col=0::Test Failures: see 'Test Results: ${{ github.job }}'"; fi
 
-  u20_gcc10_bsafe_js0_FM-2c:
+#   u20_gcc10_bsafe_js0_FM-2c:
 
-    runs-on: ubuntu-20.04
+#     runs-on: ubuntu-20.04
 
-    needs: wait_cancel_previous
+#     needs: wait_cancel_previous
 
-    steps:
-    - name: install gcc
-      run: |
-        sudo apt-get install -y gcc-10
-        sudo update-alternatives \
-          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
-          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
-          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
-          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
-    - name: checkout OpenDDS
-      uses: actions/checkout@v2.3.4
-      with:
-        path: OpenDDS
-        submodules: true
-    - name: checkout autobuild
-      uses: actions/checkout@v2.3.4
-      with:
-        repository: DOCGroup/autobuild
-        path: autobuild
-    - name: install xerces
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: sudo apt-get -y install libxerces-c-dev
-    - name: checkout MPC
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      uses: actions/checkout@v2.3.4
-      with:
-        repository: DOCGroup/MPC
-        path: MPC
-    - name: configure OpenDDS
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: |
-        cd OpenDDS
-        ./configure --compiler=g++ --safety-profile=base --tests --no-rapidjson --no-content-subscription --no-object-model-profile --no-persistence-profile --mpc=$GITHUB_WORKSPACE/MPC
-    - name: build everything
-      if: steps.cache-artifact.outputs.cache-hit != 'true'
-      run: |
-        cd OpenDDS
-        make -j4
-    - name: check build configuration
-      shell: bash
-      run: |
-        cd OpenDDS/build/target
-        . setenv.sh
-        tools/scripts/show_build_config.pl
+#     steps:
+#     - name: install gcc
+#       run: |
+#         sudo apt-get install -y gcc-10
+#         sudo update-alternatives \
+#           --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
+#           --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
+#           --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
+#           --slave /usr/bin/gcov gcov /usr/bin/gcov-10
+#     - name: checkout OpenDDS
+#       uses: actions/checkout@v2.3.4
+#       with:
+#         path: OpenDDS
+#         submodules: true
+#     - name: checkout autobuild
+#       uses: actions/checkout@v2.3.4
+#       with:
+#         repository: DOCGroup/autobuild
+#         path: autobuild
+#     - name: install xerces
+#       if: steps.cache-artifact.outputs.cache-hit != 'true'
+#       run: sudo apt-get -y install libxerces-c-dev
+#     - name: checkout MPC
+#       if: steps.cache-artifact.outputs.cache-hit != 'true'
+#       uses: actions/checkout@v2.3.4
+#       with:
+#         repository: DOCGroup/MPC
+#         path: MPC
+#     - name: configure OpenDDS
+#       if: steps.cache-artifact.outputs.cache-hit != 'true'
+#       run: |
+#         cd OpenDDS
+#         ./configure --compiler=g++ --safety-profile=base --tests --no-rapidjson --no-content-subscription --no-object-model-profile --no-persistence-profile --mpc=$GITHUB_WORKSPACE/MPC
+#     - name: build everything
+#       if: steps.cache-artifact.outputs.cache-hit != 'true'
+#       run: |
+#         cd OpenDDS
+#         make -j4
+#     - name: check build configuration
+#       shell: bash
+#       run: |
+#         cd OpenDDS/build/target
+#         . setenv.sh
+#         tools/scripts/show_build_config.pl
 
-#   ACE_TAO_u20_j_qt_ws_sec:
+# #   ACE_TAO_u20_j_qt_ws_sec:
 
 #     runs-on: ubuntu-20.04
 
